spring:
  datasource:
#    url: jdbc:postgresql://localhost:5432/portfolio_db
#    username: postgres
#    password: postgres
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true


server:
#  port: 8080
  port: ${PORT:8080}

alpha:
#  api-key: U3JL5IXPQM0YZ5YG
  api-key: ${ALPHA_API_KEY}

jwt:
#  secret: some_demo_538sjfsfj893jfJLj9483_JWT_secret_token_sdf359o5jLJJ%(%3442
  secret: ${JWT_SECRET}
  expiration: 7200000
